version: "3.9"
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      network: none
    container_name: tportfolio_api
    env_file:
      - .env
      - .env.private
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql_db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'
    healthcheck:
      test: curl -f http://localhost:7071 || exit 1
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - local
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    depends_on:
      - mysql_db
    restart: on-failure
    mem_reservation: 1G

  mysql_db:
    networks:
      - local
    container_name: tportfolio_mysql_db
    image: library/mysql:8.0
#    dns:
    mem_reservation: 1G
    volumes:
      - storage:/opt/data
    env_file:
      - .env
      - .env.private
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  storage:
networks:
  local:
    name: local-network

