tinkoff:
  api:
    token: ${TINKOFF_API_TOKEN}
    url: https://api-invest.tinkoff.ru/openapi

server:
  servlet:
    context-path:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3307/portfolio
    username: db_user
    password: j&4>TqA2

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
