tinkoff:
  api:
    token: ${TINKOFF_API_TOKEN}
    url: https://api-invest.tinkoff.ru/openapi
server:
  servlet:
    context-path:
  port: ${SPRING_DOCKER_PORT}

feign:
  client:
    config:
      default:
        loggerLevel: full
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource

  main:
    allow-bean-definition-overriding: true
