tinkoff:
  api:
    token: ${TINKOFF_API_TOKEN}
    url: https://api-invest.tinkoff.ru/openapi
alpha:
  vantage:
    api:
      url: https://query1.finance.yahoo.com/v10/finance/quoteSummary
feign:
  client:
    config:
      default:
        loggerLevel: full
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jfv
  jpa:
    hibernate:
      ddl-auto: create-drop

    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: test
