tinkoff:
  api:
    token: token
    url: invest-public-api.tinkoff.ru:443
yahoo:
  finance:
    api:
      url: https://query1.finance.yahoo.com/v10/finance/quoteSummary
server:
  servlet:
    context-path:
  port: 8080
  tomcat:
    accesslog:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3307/portfolio?allowPublicKeyRetrieval=true
    username: db_user
    password: j&4$R>TqA2

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: portfolio
  application:
    name: portfolio
